/**
 * MeMaS DP APIs
 * This is the Data Plane APIs for MeMaS (Memory Management Service).
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: max.yu@memas.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class RecollectRequest {
    'clue'?: string;
    /**
    * \"Full name of a corpus, specifying which namespace the corpus is under.  The name takes on the format of \\\"<namespace_pathname>:<corpus_name>\\\"\"
    */
    'corpusPathname'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "clue",
            "baseName": "clue",
            "type": "string"
        },
        {
            "name": "corpusPathname",
            "baseName": "corpus_pathname",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return RecollectRequest.attributeTypeMap;
    }
}

